---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include base components
resources:
  - ../../base

namespace: vote-prd

images:
  - name: backend-image
    newName: ramydockerid/vote-backend
    newTag: 2024.07.19.1
  - name: frontend-image
    newName: ramydockerid/vote-frontend
    newTag: 2024.07.19.1

patches:
  - path: backend-replicas-patch.yaml
  - path: ingress-patch.yaml
