---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: redis-image
    newName: redis
    newTag: 8.2.1

resources:
  - backend
  - frontend
  - redis
  - ingress.yaml
