---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: redis-image
    newName: redis
    newTag: 8.0.3

resources:
  - backend
  - frontend
  - redis
  - ingress.yaml
