---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include base components
resources:
  - ../../base

namespace: vote-dev

images:
  - name: backend-image
    newName: ramydockerid/vote-backend
    newTag: 2025.07.26.16543231189
  - name: frontend-image
    newName: ramydockerid/vote-frontend
    newTag: 2025.07.26.16543231189

patches:
  - path: ingress-patch.yaml
