name: ci pipeline

on:
  push:

jobs:
  # -------------------------
  lint:
    name: Lint YAML files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install yamllint
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint

      - name: Run yamllint
        run: yamllint k8s/

  # -------------------------
  validate-kustomize:
    name: Validate overlays (${{ matrix.env }})
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        env: [dev, staging, prod]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install kustomize and kubeconform
        run: |
          curl -sSL https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz | tar -xz -C /usr/local/bin kubeconform
          chmod +x /usr/local/bin/kubeconform

          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/

      - name: Validate ${{ matrix.env }} overlay
        run: |
          kustomize build k8s/overlays/${{ matrix.env }} | kubeconform -strict -summary || exit 1
