name: Run Renovate on Dispatch

on:
  repository_dispatch:
    types: [trigger-renovate]

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v40.3.6
        with:
          token: ${{ secrets.TRIGGER_PAT }}
