name: Run Renovate on Dispatch

on:
  repository_dispatch:
    types: [trigger-renovate]

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.3
        with:
          token: ${{ secrets.TRIGGER_PAT }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_PLATFORM: github
          RENOVATE_CONFIG_FILE: renovate.json
          RENOVATE_BASE_BRANCH: main
          RENOVATE_LOG_LEVEL: debug

  wait-for-dev-merge:
    needs: renovate
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.TRIGGER_PAT }}
      REPO: ${{ github.repository }}
    steps:
      - name: Wait for Renovate PR to auto-merge into dev
        run: |
          for i in {1..60}; do
              PR_ID=$(gh pr list \
                --repo https://github.com/"$REPO" \
                --label "env::dev" \
                --json number,title \
                --jq '.[] | select(.title | test("^chore\\(deps\\): update")) | .number')
            
              if [ -n "$PR_ID" ]; then
                echo "No merged PR yet. Retrying in 5 seconds..."
                sleep 5
              else
                echo "Found merged Renovate PR"
                exit 0
              fi
          done

          echo "Timeout: PR was not merged after waiting."
          exit 1

#  trigger-e2e:
#    runs-on: ubuntu-latest
#    needs: wait-for-dev-merge
#
#    steps:
#      - name: Trigger E2E tests in VoteApp repository
#        run: |
#          curl -X POST \
#            -H "Authorization: token ${{ secrets.TRIGGER_PAT }}" \
#            -H "Accept: application/vnd.github.v3+json" \
#            https://api.github.com/repos/RamyChaabane/VoteApp/dispatches \
#            -d '{"event_type":"trigger-e2e"}'
