name: Run Renovate on Dispatch

on:
  repository_dispatch:
    types: [trigger-renovate]

jobs:
  pre-renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Print triggered version
        run: echo "${{ github.event.client_payload.version }}" > version.txt

      - name: Upload version artifact
        uses: actions/upload-artifact@v4
        with:
          name: version-${{ github.event.client_payload.version }}
          path: version.txt

  renovate:
    runs-on: ubuntu-latest
    needs: pre-renovate

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.3
        with:
          token: ${{ secrets.TRIGGER_PAT }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_PLATFORM: github
          RENOVATE_CONFIG_FILE: renovate.json
          RENOVATE_BASE_BRANCH: main
          RENOVATE_LOG_LEVEL: debug
